### ISSUE TITLE
TODO-List for p2-repo

### ISSUE THREAD

**Issue by Squareys** [knime-ip/knip-externals#8]
The following steps still need to be completed until p2-repo branch is ready for use:

- [x] pack generated feature.xml in jars
- [x] Figure out how to make p2-maven-plugin find generated feature jars
- [x] Automatically add generated features (hopefully with p2-maven-plugin) to content.xml
- [x] Test whether downloading features from update site works
- [ ] Add all dependencies to feature_list.xml

**Comment by Squareys** [comment]
We now build the update site with tycho and wrap maven artifacts as bundles with apache felix ourselves instead. Therefore this issue does not apply anymore. 

Reasoning: m2-maven-plugin does not add Require-Bundle information to the wrapped bundle manifests. This information is required for eclipse to automatically resolve dependencies on update sites.
